spring.application.name=expense-tracker
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/expense_tracker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
logging.level.org.hibernate.SQL=${HIBERNATE_SQL_LOG_LEVEL:INFO}
server.port=8080

jwt.secretKey=${JWT_SECRET_KEY:my-super-secret-key-which-is-at-least-32-characters-long}
jwt.expiration=${JWT_EXPIRATION:3600000}
